name: Python Workflow

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate UML
      run: |
        sudo apt install graphviz
        pyreverse -o png my_module
    - name: Upload class diagram
      uses: actions/upload-artifact@v2
      with:
        name: class-diagram
        path: classes.png


    #- run: python my_script.py
